name: Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install backend dependencies and start server
      run: |
        cd backend
        npm ci
        npm start &
        echo "Backend server started"
        sleep 10
        curl -f http://localhost:3000 || true
        
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Install Playwright browsers
      run: |
        cd frontend
        npx playwright install chromium
        
    - name: Start frontend server in background
      run: |
        cd frontend
        npm run dev &
        echo "Frontend server started in background"
        sleep 15
        curl -f http://localhost:5173 || true
        
    - name: Run frontend tests with Playwright
      env:
        GOOGLE_TEST_EMAIL: ${{ secrets.GOOGLE_TEST_EMAIL }}
        GOOGLE_TEST_PASSWORD: ${{ secrets.GOOGLE_TEST_PASSWORD }}
      run: |
        cd frontend
        npx playwright test --workers=1 --headed