name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies for backend
      run: cd backend && npm ci
    - name: Install dependencies for frontend
      run: cd frontend && npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start backend dev server
      run: cd backend && npm run dev &
    - name: Start frontend dev server
      run: cd frontend && npm run dev &
    - name: Wait for servers to be ready
      run: sleep 10  # Adjust sleep time as needed to ensure servers are up
    - name: Run Playwright tests
      run: cd frontend && npx playwright test --workers=1
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
