name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Navigate to backend and install dependencies
      run: |
        cd backend
        npm ci
        
    - name: Start server in background
      run: |
        cd backend
        npm start &
        echo "Server started in background (Node.js v22)"
        # Wait for server to be ready
        sleep 10
        # Optional: Check if server is responding
        curl -f http://localhost:3000 || true
      
    - name: Run tests
    
      run: |
        cd backend && ls
        npm run test