name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Vitest Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies for frontend
      run: npm ci
      working-directory: frontend

    - name: Install dependencies for backend
      run: npm ci
      working-directory: ./backend

    - name: Start backend app
      run: npm run dev &
      working-directory: ./backend

    - name: Wait for backend to be ready
      run: sleep 10  # Adjust sleep time as needed to ensure backend is up

    - name: Run tests with Vitest
      run: npm run test:run
      working-directory: ./backend
