name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Vitest Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies for frontend
      run: cd frontend && npm ci

    - name: Install dependencies for backend
      run: cd backend && npm ci

    - name: Start backend app
      run: cd backend && npm run dev &

    - name: Wait for backend to be ready
      run: sleep 10  # Adjust sleep time as needed to ensure backend is up

    - name: Run tests with Vitest
      run: cd backend && npm test

    - name: Upload test results
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: vitest-results
        path: backend/test-results/
        retention-days: 30
