name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies using npm ci
      - name: Install dependencies
        run: npm install && npm ci
        working-directory: ./backend

      # Run tests
      - name: Run tests
        working-directory: ./backend
        env:
          API_PREFIX: ${{ secrets.API_PREFIX }}
        run: npm run test
